routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/aboutUs', function () {
    return view('front.about');
});

Route::get('/contactUs', function () {
    return view('front.contact');
});

Route::get('/viewTeam', function () {
    return view('front.team');
});

Route::get('/viewJobs', function () {
    return view('front.jobs');
});

Route::get('/apply/{id}', function ($id) {
    return view('front.apply', ['jobId' => $id]);
});

Route::get('/categoryJobs/{id}', 'JobController@jobsOfCategory');

Route::get('/selectionProcess', function () {
    return view('front.selectionProcess');
});

Route::post('/searchJobs', 'JobController@searchJobs');

Route::post('/applyForJob', 'CVController@applyForJob');

Route::get('/home', function(){
  return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index');
Route::post('/saveProfile', 'UserController@saveProfile');
Route::get('/updateProfile', 'UserController@updateProfile');

//Users
Route::resource('users', 'UserController');

//About us
Route::resource('/abouts', 'AboutController');
Route::get('/abouts_changestatus/{id}', 'AboutController@changestatus');
Route::get('/deleteAboutImage/{id}', 'AboutController@deleteAboutImage');

//Email
Route::resource('/emails', 'EmailController');
Route::get('/emails_changestatus/{id}', 'EmailController@changestatus');

//Contact
Route::resource('/contacts', 'ContactController');
Route::get('/contacts_changestatus/{id}', 'ContactController@changestatus');

//Address
Route::resource('/addresses', 'AddressController');
Route::get('/addresses_changestatus/{id}', 'AddressController@changestatus');

//Social
Route::resource('/socials', 'SocialController');
Route::get('/socials_changestatus/{id}', 'SocialController@changestatus');

//Stat
Route::resource('/stats', 'StatController');
Route::get('/stats_changestatus/{id}', 'StatController@changestatus');

//Message
Route::resource('/messages', 'MessageController');
Route::get('/messages_changestatus/{id}', 'MessageController@changestatus');

//Services
Route::resource('/services', 'ServiceController');
Route::get('/services_changestatus/{id}', 'ServiceController@changestatus');

//Selection Process
Route::resource('/selectionProcesses', 'SelectionProcessController');
Route::get('/selectionProcesses_changestatus/{id}', 'SelectionProcessController@changestatus');

//Categories
Route::resource('/categories', 'CategoryController');
Route::get('/categories_changestatus/{id}', 'CategoryController@changestatus');

//Teams
Route::resource('/teams', 'TeamController');
Route::get('/teams_changestatus/{id}', 'TeamController@changestatus');

//CareerTips
Route::resource('/careerTips', 'CareerTipController');
Route::get('/careerTips_changestatus/{id}', 'CareerTipController@changestatus');

//Job Side Images
Route::resource('/jobSideImages', 'JobSideImageController');
Route::get('/jobSideImages_changestatus/{id}', 'JobSideImageController@changestatus');

//How It Works
Route::resource('/hows', 'HowController');
Route::get('/hows_changestatus/{id}', 'HowController@changestatus');

//Jobs
Route::resource('/jobs', 'JobController');
Route::get('/jobs_changestatus/{id}', 'JobController@changestatus');

//CVs
Route::resource('/cvs', 'CVController');
Route::get('/cvs_changestatus/{id}', 'CVController@changestatus');

//Images
Route::resource('/images', 'ImageController');
Route::get('/images_changestatus/{id}', 'ImageController@changestatus');

//Maps
Route::resource('/maps', 'MapController');
Route::get('/maps_changestatus/{id}', 'MapController@changestatus');

//Notifications
Route::resource('/notifications', 'NotificationController');
Route::get('/notifications_changestatus/{id}', 'NotificationController@changestatus');

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    //
}

app/Address.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Address extends Model
{
    //
}

app/CV.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CV extends Model
{
    protected $table = 'c_vs';
}

app/CareerTip.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CareerTip extends Model
{
    //
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
}

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
}

app/Email.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Email extends Model
{
    //
}

app/How.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class How extends Model
{
    //
}

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    //
}

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    //
}

app/JobSideImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobSideImage extends Model
{
    //
}

app/Map.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Map extends Model
{
    //
}

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    //
}

app/Notification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    //
}

app/SelectionProcess.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SelectionProcess extends Model
{
    //
}

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    //
}

app/Social.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Social extends Model
{
    //
}

app/Stat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stat extends Model
{
    //
}

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/dashboard/abouts.blade.php
@extends('layouts.dashboardlayout')
@section('content')
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <?php
      $abouts = \App\About::all();
      ?>
      @if(!isset($about) && $abouts->isEmpty())
      <div class="card">
        <div class="card-header">
          <h5 class="title">Add About Us</h5>
        </div>
        <div class="card-body">
          <form role="form" action="/abouts" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Title</label>
                  <input type="text" class="form-control" placeholder="Title" name="title" required>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                  <button class="btn btn-primary">
                    Choose Files<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png" required>
                  </button>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label>Details</label>
                  <textarea rows="10" class="form-control" placeholder="Details" name="detail"></textarea>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
          </form>
        </div>
      </div>
      @else
      <div class="card">
        <?php
        $about = \App\About::first();
        ?>
        <div class="card-header">
          <h5 class="title">Edit About us</h5>
        </div>
        <div class="card-body">
          <div class="row">
            @if(!empty($about->picturePath))
            <div class="col-md-6 text-center">
              <img src="{{asset('aboutpage/images/').'/'.$about->picturePath}}" alt="About Image" />
              <a type="link" class="btn btn-danger btn-sm" href="/deleteAboutImage/<?php echo $about->id; ?>">Delete</a>
            </div>
            @endif
          </div>
          <form role="form" action="/abouts/<?php echo $about->id;?>" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{method_field('PUT')}}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Title</label>
                  <input type="text" class="form-control" placeholder="Title" name="title" required value="{{$about->title}}">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                  <button class="btn btn-primary">
                    Choose Files<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png">
                  </button>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label>Details</label>
                  <textarea rows="10" class="form-control" placeholder="Details" name="detail">{{$about->detail}}</textarea>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
          </form>
        </div>
      </div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">About Us</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <tr>
                  <th>Id</th>
                  <th>Title</th>
                  <th>Image</th>
                  <th>Status</th>
                  <th class="text-right">Control Section</th>
                </tr>
              </thead>
              <tbody>
                <?php
                $abouts = \App\About::all();
                ?>
                @foreach($abouts as $value)
                <tr>
                  <td>{{$value->id}}</td>
                  <td>{{$value->title}}</td>
                  <td>
                    @if(!empty($value->picturePath))
                    <img src="{{asset('aboutpage/images/').'/'.$value->picturePath}}" alt="About Image" width="100" height="100" />
                    @endif
                  </td>
                  <td>{{$value->status}}</td>
                  <td class="text-right">
                    <a type="link" class="btn btn-default btn-sm" href="/abouts_changestatus/<?php echo $value->id;?>">Change Status</a>
                    <a type="link" class="btn btn-info btn-sm" href="/abouts/<?php echo $value->id;?>/edit">Edit</a>
                    <form action="{{ route('abouts.destroy', $value->id) }}" method="post" style="display:inline">
                      {{ method_field('DELETE') }}
                      {{ csrf_field() }}
                      <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                    </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/careerTips.blade.php
@extends('layouts.dashboardlayout')
@section('content')

  <div class="content">
    <div class="row">
      <div class="col-md-12">
        @if(!isset($careerTip))
        <div class="card">
          <div class="card-header">
            <h5 class="title">Add Career Tip</h5>
          </div>
          <div class="card-body">
            <form role="form" action="/careerTips" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" name="title" required>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png" required>
                    </button>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Detail</label>
                    <textarea name="detail" class="form-control" placeholder="Detail"></textarea>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @else
        <div class="card">
          <div class="card-header">
            <h5 class="title">Edit Career Tip</h5>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-3">
                <img src="{{asset('careerTipsData/images/').'/'.$careerTip->picturePath}}" alt="Career Tip Image" class="img img-responsive" />
              </div>
            </div>
            <form role="form" action="/careerTips/<?php echo $careerTip->id;?>" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{method_field('PUT')}}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" name="title" required value="{{$careerTip->title}}">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                    <small>If you want to change the old image you can upload the new one it will replace the old one. Otherwise, leave it empty.</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png">
                    </button>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Detail</label>
                    <textarea name="detail" class="form-control" placeholder="Detail">{{$careerTip->detail}}</textarea>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Career Tips</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Detail</th>
                    <th>Status</th>
                    <th class="text-right">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $careerTips = \App\CareerTip::all();
                  ?>
                  @foreach($careerTips as $value)
                  <tr>
                    <td>{{$value->id}}</td>
                    <td><img src="{{asset('careerTipsData/images/').'/'.$value->picturePath}}" alt="Team Member Image" width="100" height="100" /></td>
                    <td>{{$value->title}}</td>
                    <td>{{$value->detail}}</td>
                    <td>{{$value->status}}</td>
                    <td class="text-right">
                      <a type="link" class="btn btn-default btn-sm" href="/careerTips_changestatus/<?php echo $value->id;?>">Change Status</a>
                      <a type="link" class="btn btn-info btn-sm" href="/careerTips/<?php echo $value->id;?>/edit">Edit</a>
                      <form action="{{ route('careerTips.destroy', $value->id) }}" method="post" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/dashboard/categories.blade.php
@extends('layouts.dashboardlayout')
@section('content')

  <div class="content">
    <div class="row">
      <div class="col-md-12">
        @if(!isset($category))
        <div class="card">
          <div class="card-header">
            <h5 class="title">Add Category</h5>
          </div>
          <div class="card-body">
            <form role="form" action="/categories" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Name</label>
                    <input type="text" class="form-control" placeholder="Name" name="name" required>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Icon</label>
                    <input type="text" class="form-control" placeholder="Icon" name="icon" required>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png" required>
                    </button>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @else
        <div class="card">
          <div class="card-header">
            <h5 class="title">Edit Category</h5>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-3">
                <img src="{{asset('categoriesData/images/').'/'.$category->picturePath}}" alt="Category Image" class="img img-responsive" />
              </div>
            </div>
            <form role="form" action="/categories/<?php echo $category->id;?>" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{method_field('PUT')}}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Name</label>
                    <input type="text" class="form-control" placeholder="Name" name="name" required value="{{$category->name}}">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Icon</label>
                    <input type="text" class="form-control" placeholder="Icon" required name="icon" value="{{$category->icon}}">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                    <small>If you want to change the old image you can upload the new one it will replace the old one. Otherwise, leave it empty.</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png">
                    </button>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Selection Processes</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th class="text-right">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $categories = \App\Category::all();
                  ?>
                  @foreach($categories as $value)
                  <tr>
                    <td>{{$value->id}}</td>
                    <td><img src="{{asset('categoriesData/images/').'/'.$value->picturePath}}" alt="Category Image" width="100" height="100" /></td>
                    <td>{{$value->name}}</td>
                    <td>{{$value->status}}</td>
                    <td class="text-right">
                      <a type="link" class="btn btn-default btn-sm" href="/categories_changestatus/<?php echo $value->id;?>">Change Status</a>
                      <a type="link" class="btn btn-info btn-sm" href="/categories/<?php echo $value->id;?>/edit">Edit</a>
                      <form action="{{ route('categories.destroy', $value->id) }}" method="post" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/dashboard/cvs.blade.php
@extends('layouts.dashboardlayout')
@section('content')

  <div class="content">
    <div class="row">
      <div class="col-md-12">
        @if(isset($cv))
        <div class="card">
          <div class="card-header">
            <h5 class="title">View Candidate</h5>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Name</label>
                  <p>{{$cv->name}}</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Phone</label>
                  <p>{{$cv->phone}}</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Email</label>
                  <p>{{$cv->email}}</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>CV</label>
                  <p><a href="{{asset('cvsData/documents/').'/'.$cv->cvPath}}" target="_blank">CV</a></p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Job Status</label>
                  <p>{{$cv->jobStatus}}</p>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label>Comments</label>
                  <p>{{$cv->comments}}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">CV's</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th class="text-right">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $cvs = \App\CV::all();
                  ?>
                  @foreach($cvs as $value)
                  <tr>
                    <td>{{$value->id}}</td>
                    <td>{{$value->name}}</td>
                    <td>{{$value->phone}}</td>
                    <td>{{$value->email}}</td>
                    <td>{{$value->status}}</td>
                    <td class="text-right">
                      <a type="link" class="btn btn-default btn-sm" href="/cvs_changestatus/<?php echo $value->id;?>">Change Status</a>
                      <a type="link" class="btn btn-info btn-sm" href="/cvs/<?php echo $value->id;?>">View</a>
                      <form action="{{ route('cvs.destroy', $value->id) }}" method="post" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete" />
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/dashboard/jobSideImages.blade.php
@extends('layouts.dashboardlayout')
@section('content')

  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h5 class="title">Add Job Side Image</h5>
          </div>
          <div class="card-body">
            <form role="form" action="/jobSideImages" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Direction</label>
                    <select class="form-control" name="direction">
                      <option>Left</option>
                      <option>Right</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png" required>
                    </button>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Job Side Images</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Direction</th>
                    <th>Status</th>
                    <th class="text-right">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $jobSideImages = \App\JobSideImage::all();
                  ?>
                  @foreach($jobSideImages as $value)
                  <tr>
                    <td>{{$value->id}}</td>
                    <td><img src="{{asset('jobSideImagesData/images/').'/'.$value->picturePath}}" alt="Job Side Image" width="100" height="100" /></td>
                    <td>{{$value->direction}}</td>
                    <td>{{$value->status}}</td>
                    <td class="text-right">
                      <a type="link" class="btn btn-default btn-sm" href="/jobSideImages_changestatus/<?php echo $value->id;?>">Change Status</a>
                      <a type="link" class="btn btn-info btn-sm" href="/jobSideImages/<?php echo $value->id;?>/edit" hidden>Edit</a>
                      <form action="{{ route('jobSideImages.destroy', $value->id) }}" method="post" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection